### ISSUE TITLE
Including rules for jshint/csslint and not htmlhint makes htmlhint return nothing.

### ISSUE THREAD

**Issue by cfjedimaster** [thedaviddias/HTMLHint#106]
In my testing, I've got a rule for jshint and one for csslint, but I've not specified anything for htmlhint itself. So the config passed to it looks like so:

{"jshint":{"undef":true,"predef":[]},"csslint":{"order-alphabetical":false}}

However - HTMLHint then returns no errors on the input as it acts as if it were told no rules existed. 

I guess that makes sense - but it seems like there is no way to say, "Do JSHint/CSSLint and your default rules". Correct?

**Comment by yaniswang** [comment]
It not makes sense, you can see: https://github.com/yaniswang/HTMLHint/blob/master/test/rules/jshint.spec.js

Only pass jshint config, and it run successed.

**Comment by thedaviddias** [comment]
Hi @cfjedimaster, that issue seems pretty old, do you mind closing the issue? Thanks.

**Comment by cfjedimaster** [comment]
I honestly have no idea if this is an issue or not so will close it. The comment from @yaniswang said "only pass jshint" - but what of my original issue of passing jshint and csslint?

**Comment by thedaviddias** [comment]
@cfjedimaster Can't tell you, but we'll be moving to ESLint and Stylelint soon...

**Comment by cfjedimaster** [comment]
Good enough for me. :)
