### ISSUE TITLE
Console output has typo

### ISSUE THREAD

**Issue by willsteinmetz** [thedaviddias/HTMLHint#125]
In version 0.9.12, when displaying the name of the file, the line starts with "HtmlHintPuls" instead of "HtmlHintPlus".

**Comment by yaniswang** [comment]
Can you show more info? I don't understand.

**Comment by willsteinmetz** [comment]
I'm having trouble finding it at the moment but definitely see it when it is run at work. When I get in on Monday, I'll try to find it. It's possible that it has been fixed in a more recent version. When I get it narrowed down, I will update this.

**Comment by thedaviddias** [comment]
Hey @willsteinmetz, the issue seems old, are you able to close that issue? Thanks.

**Comment by willsteinmetz** [comment]
@thedaviddias My bad, I thought it was. Will do that now.
