### ISSUE TITLE
.htmlhintrc not used by default

### ISSUE THREAD

**Issue by remcohaszing** [thedaviddias/HTMLHint#163]
The [usage docs](https://github.com/yaniswang/HTMLHint/wiki/Usage) state that `.htmlhintrc` from the current working directory is used by default.

> search .htmlhintrc file in current directory and all parent directories:
> 
> ```
> htmlhint
> htmlhint test.html
> ```

No default `.htmlhintrc` file is actually used.

**Comment by ChrisAitken** [comment]
+1 I am currently getting that issue as well.

**Comment by phaux** [comment]
Same issue here. I added a few `console.log`s and it seems that it quits the loop one iteration too soon and skips checking the root.

So when doing `htmlhint foo/bar/baz/**/*.html` it first figures out the root of the glob which is `foo/bar/baz` and checks `foo/bar/baz`, `foo/bar` and `foo`. It never checks empty string path

**Comment by daviddiasdigital** [comment]
Someone is working on that?

**Comment by phaux** [comment]
@daviddiasdigital I fixed it in #181

**Comment by trisys3** [comment]
@phaux Yes, but it looks like it was not fully merged yet.
