### ISSUE TITLE
Make csslint & jshint optional

### ISSUE THREAD

**Issue by schmod** [thedaviddias/HTMLHint#174]
Would you consider making csslint and jshint `optionalDependencies` to reduce the overall payload of this module?

Both csslint and jshint bring in several of their own dependencies, and likely aren't used very often by HTMLHint users, given that inline styles/scripts have become less common over time.

**Comment by sinedied** [comment]
In the first place, why are they even part of the package dependencies? These belongs to the devDependencies, unless I missed something?
All build/test/lint related tasks should be done in the `prepublish` npm script, so these kind of dependencies should not be needed by the distribution package.

**Comment by ArmorDarks** [comment]
Those indeed seems to be optional dependencies, especially considering that most people today relies on ESLint and Stylelint.

**Comment by thedaviddias** [comment]
@ArmorDarks We'll be moving to ESLint and Stylelint soon :)

**Comment by thedaviddias** [comment]
Duplicate with #167
