### ISSUE TITLE
update jshint: 2.9.4

### ISSUE THREAD

**Issue by bonesoul** [thedaviddias/HTMLHint#194]
https://snyk.io/vuln/npm:cli:20160615
Insecure use of /tmp folderSEVERITY: LOW
Discovered in a nested dependency:grunt-htmlhint-plus@0.4.2htmlhint@0.9.13jshint@2.8.0cli@0.6.6

https://snyk.io/vuln/npm:cli:20160615
Regular Expression Denial of ServiceSEVERITY: HIGH
Discovered in a nested dependency:grunt-htmlhint-plus@0.4.2htmlhint@0.9.13jshint@2.8.0minimatch@2.0.10

Please update to 2.9.4 so we can have a safe version.

**Comment by thedaviddias** [comment]
Solved by #260 and #251
